first = int(input("Give me the first number: "))
second = int(input("Give me the second number: "))
print(f"Thank you!\n{first} + {second} = {first + second}")
print(f"{first} - {second} = {first - second}") 
print(f"{first} / {second} = {int(first / second)}")
print(f"{first} * {second} = {first * second}")
